# @format
---
# Organization settings in Azure will require a comment to
# allow the PR build proceed
pr:
  autoCancel: true
  branches:
    include:
      - "*"

trigger:
  batch: false
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

#variables:
#  GOROOT: /usr/local/go

variables:
  GOPATH: '$(Agent.HomeDirectory)/go' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go'
  # GOROOT: '/opt/hostedtoolcache/go/1.21.8/x64' # Go installation path

pool:
  vmImage: ubuntu-22.04

stages:
  - template: .azure-pipelines/templates/01_lint.yaml
