# @format
---
steps:
  - task: Bash@3
    displayName: Install dependencies
    inputs:
      targetType: "inline"
      workingDirectory: "$(Build.Repository.LocalPath)"
      failOnStderr: false
      noProfile: true
      noRc: true
      script: |
        if [ -z "$(command -v make)" ]; then
          apt-get update -y -qq && apt-get install -y -qq build-essential sudo
        fi
        rm -rf "${GOROOT_AZURE_AGENT}" || true
        rm -rf "${AZURE_TOOLS_CACHE}" || true
        make install_deps
        source "${HOME}/.asdf/asdf.sh"
        tofu version
